START TRANSACTION; # 트랜잭션 시작
# BEGIN / BEGIN WORK 같은 의미
USE SHOPPINGMALL;

# FOO002 가격을 2000원으로 수정
UPDATE PRODUCT SET PR_PRICE = 2000 WHERE PR_CODE = 'FOO002';

SAVEPOINT A;	# 저장명은 임의의 A

UPDATE PRODUCT SET PR_PRICE = 1000 WHERE PR_CODE = 'FOO002';

ROLLBACK TO A;	# ROOLBACK은 START TRANSACTION 전으로 돌리는 것

COMMIT; 		# 지금까지 했던 작업을 고정 반영함
SELECT * FROM PRODUCT;